name: derp code sync 

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ROM on Self-hosted
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Initialize Repo
        run: |
          wget https://raw.githubusercontent.com/akhilnarang/scripts/refs/heads/master/setup/android_build_env.sh
          chmod u+x android_build_env.sh
          ./android_build_env.sh
          mkdir derp && cd derp
          repo init -u https://github.com/DerpFest-LOS/android_manifest.git -b 15.2 --git-lfs
          repo sync -j20
